# Generated by Django 4.2.3 on 2023-07-18 18:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=30, verbose_name='Модель')),
                ('color', models.CharField(choices=[('черный', 'черный'), ('желтый', 'желтый'), ('белый', 'белый'), ('синий', 'синий'), ('зеленый', 'зеленый'), ('красный', 'красный')], max_length=30, verbose_name='Цвет')),
                ('power', models.IntegerField(verbose_name="Мощность'")),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
                'ordering': ['year', 'model'],
            },
        ),
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('age', models.IntegerField(null=True, verbose_name='Возраст')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Vash nomer telefona', max_length=31, unique=True, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Эл. почта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['last_name'],
                'unique_together': {('first_name', 'last_name', 'email')},
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя водителя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия водителя')),
                ('birthday', models.DateField(default=datetime.date.today, verbose_name='Дата рождения')),
                ('city', models.CharField(max_length=100, null=True, verbose_name='Город')),
                ('passport', models.CharField(default='', max_length=15, unique=True, verbose_name='Паспорт')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Эл. почта')),
                ('is_activated', models.BooleanField(default=True, verbose_name='Активация')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
                'ordering': ['last_name', '-birthday'],
                'unique_together': {('first_name', 'last_name', 'passport')},
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('position', models.CharField(max_length=50, verbose_name='Должность')),
                ('education', models.CharField(choices=[('middle', 'среднее'), ('high', 'высшее'), ('professional', 'профессиональное')], max_length=30)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='car', to='myapp.car', verbose_name='машина')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='car', to='myapp.client', verbose_name='Клиент')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='driver', to='myapp.driver', verbose_name='водитель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='myapp.carbrand', verbose_name='Марка'),
        ),
    ]
