# Generated by Django 4.2.3 on 2023-07-18 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birthday',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата рождения'),
        ),
    ]
