# Generated by Django 4.2.3 on 2023-07-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_client_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='age',
            field=models.IntegerField(null=True, verbose_name='Возраст'),
        ),
    ]
