# Generated by Django 4.2.1 on 2023-06-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_client_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='age',
            field=models.IntegerField(null=True, verbose_name='Возраст'),
        ),
    ]
